name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+1
  url_launcher: ^6.2.4  # Use the latest version available
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  intl: ^0.18.1
  file_picker: ^4.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flutter_file_downloader: ^1.2.1
  paytm_allinonesdk: ^1.2.4
  local_auth: ^2.1.6
  flutter_contacts: ^1.1.9
  permission_handler: ^11.3.1
  table_calendar: ^3.0.9
  syncfusion_flutter_signaturepad: ^26.2.8
  camera: ^0.11.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    #- images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
